### ISSUE TITLE
What is this project's license?

### ISSUE THREAD

**Issue by DidgetyTech** [format-message/icu-message-format-for-translators#5]
Thanks for the wonderful editor. I'm interested in using it at work, but first need to know the license for the repository. Thanks!

**Comment by vanwagonet** [comment]
I've currently got MIT specified in the package.json, but I haven't bothered to put the license text into a file. Does that license work for you, or is another more amendable to your purposes?

**Comment by DidgetyTech** [comment]
MIT is perfect. Thanks!
