### ISSUE TITLE
Page looks weird in Chrome

### ISSUE THREAD

**Issue by ipanasenko** [format-message/icu-message-format-for-translators#6]
Hi!
Using Chrome on Mac, and see this:

![image](https://user-images.githubusercontent.com/576152/44668977-81a01a80-aa27-11e8-87c3-ae33d5f39a98.png)

**Comment by vanwagonet** [comment]
Thanks for pointing it out. I made a change and it seems to be working much better now.

**Comment by ipanasenko** [comment]
It indeed does. Thanks!
